server:
  port: 8120

spring:
  application:
    name: loyalty
  datasource:
    username: rafavilomar
    url: jdbc:postgresql://localhost:5432/loyalty
    password: rafavilomar
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://localhost:9411

grpc:
  server:
    port: 8083

#kafka:
#  bootstrap-address: localhost:29092
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true
#    enabled: true
