server:
  port: 8080
  contextPath: /swagger2-demo

spring:
  application:
    name: customer
  datasource:
    username: rafavilomar
    url: jdbc:postgresql://localhost:5432/customer
    password: rafavilomar
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://localhost:9411

kafka:
  bootstrap-address: localhost:29092

springdoc:
  show-login-endpoint: true
  api-docs:
    path: /v2/api-docs

jwt:
  secret-key: fewe6rt46321g3w54re5w1f32s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
