server:
  port: 8080
  contextPath: /swagger2-demo

spring:
  application:
    name: customer
  datasource:
    username: ${DB_USERNAME}
    url: jdbc:postgresql://localhost:5432/customer
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /v2/api-docs

grpc:
  server:
    port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
    fetch-registry: true
    register-with-eureka: true
    enabled: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
