server:
  port: 8085
  contextPath: /swagger2-demo

spring:
  application:
    name: product
  datasource:
    username: ${DB_USERNAME}
    url: jdbc:postgresql://localhost:5432/product
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: ${ZIPKIN_URL}

springdoc:
  api-docs:
    path: /v2/api-docs

grpc:
  server:
    port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
    fetch-registry: true
    register-with-eureka: true
    enabled: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
