server:
  port: 8085
  contextPath: /swagger2-demo

spring:
  application:
    name: product
  datasource:
    username: rafavilomar
    url: jdbc:postgresql://localhost:5432/product
    password: rafavilomar
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://localhost:9411

springdoc:
  api-docs:
    path: /v2/api-docs

grpc:
  server:
    port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

jwt:
  secret-key: jwt
