services:
  loyalty:
    container_name: loyalty
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    env_file: ../.env
    networks:
      - postgres
      - apps
    ports:
      - "8120:8120"
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
    external: true
  apps:
    driver: bridge
    external: true