server:
  port: 8150

spring:
  application:
    name: shopping
  jpa:
  zipkin:
    base-url: http://localhost:9411

kafka:
  bootstrap-address: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true