services:
  security:
    container_name: security
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    env_file: ../.env
    networks:
      - postgres
      - apps
    ports:
      - "8090:8090"
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
    external: true
  apps:
    driver: bridge
    external: true