server:
  port: 8095

spring:
  application:
    name: email-notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_EMAIL_USERNAME}
    password: ${SMTP_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  zipkin:
#    base-url: http://localhost:9411

kafka:
  bootstrap-address: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
