server:
  port: 8090
  contextPath: /swagger2-demo

spring:
  application:
    name: security
  datasource:
    username: rafavilomar
    url: jdbc:postgresql://localhost:5432/security
    password: rafavilomar
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://localhost:9411

springdoc:
  api-docs:
    path: /v2/api-docs

kafka:
  bootstrap-address: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

jwt:
  secret-key: jwt