services:
  product:
    container_name: product
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    env_file: ../.env
    networks:
      - postgres
      - apps
    ports:
      - "8085:8085"
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
    external: true
  apps:
    driver: bridge
    external: true